version: '3'
services:
  app:
    build:
      context: .
      args:
        RUBY_VERSION: '2.7.1'
        NODE_MAJOR: '14'
        YARN_VERSION: '1.22.4'
    volumes:
      - .:/webapp
    ports:
      - "3000:3000"
